### ISSUE TITLE
Thoughts on further developnent

### ISSUE THREAD

**Issue by mkikets99** [krglaws/MyLFS#7]
There is no "Discussion" section so typing here.

It is a preatty well made script for making a LFS image.
But i have some thoughts and ideas that can be done here.

1. I think it would be better to have a option of build iso or img (depending of needs of person) or even combine both with SquashFS. What do you think of this?
2. Chunk of script is pretty good at handling modules or aka `additional phases`. What if script will have ability to build BLFS and even CLFS? And also person can deside what packages he want by providing something like `config name` which will be a txt with packages from blfs/clfs he/she wants to install. How about that?
3. Making a named file structure can be hard for some people, when put in a folder like structure is much easier to operate.... Idk, maybe it's only hard for me, but having a folder-like stucture for `static` and `templates` will be easier for me. (If path detection is an issue, `find` command is for help)

Currently i'll create a separate branch for making BLFS posible and will fix some folder naming to make it easier. Maybe i'll edit function to be universal for this task...

Maybe you have some thoughts to make something for this to be usefull?

**Comment by krglaws** [comment]
> 1...

I completely agree. I'm not familiar with SquashFS, nor with how ISO filesystems work, but as I mentioned in the other issue, it looks like you brought some good starting places to get an ISO working.

> 2...

The point of the "extension" capability was so that you could add BLFS scripts (and completely custom scripts) to your build. I don't like the idea of maintaining those scripts in this project though, I think that would be too much. I was thinking it would be better for people to keep their own BLFS scripts in a separate repositories that they would just maintain on their own. It sounds like you are already planning a branch for this though, so I'll remain open to the idea if things don't get too crazy.

As for CLFS, that might be too much too. At least for me. I don't know it that well, but looking at it, it looks like the script would need to juggle instructions from NINE different books http://www.clfs.org/view/CLFS-3.0.0-SYSVINIT/. And that's just for SysVinit.

> 3...

I agree with this. I was already thinking of doing this instead of the way the script currently does it.


Personally, I think the priorities should be:
1. Provide the option to build SystemD instead of only SysVInit.
2. Provide the option to either directly build or convert IMG files into VM bootable ISO files (as you already mentioned).
3. Provide the option to use UEFI instead of only legacy BIOS. I kinda gave up on this one since it seemed to me that most people don't bother with UEFI. But I'd kinda like to take another crack at it at some point.

**Comment by mkikets99** [comment]
Ok. So...
What if to change section 2 into abillity to build a multi_phased extension? Like a blfs....

This will be helpful, i think...

**Comment by mkikets99** [comment]
> 3\. Provide the option to use UEFI instead of only legacy BIOS. I kinda gave up on this one since it seemed to me that most people don't bother with UEFI. But I'd kinda like to take another crack at it at some point.

As i remember correctly, they can work both together.

**Comment by krglaws** [comment]
> What if to change section 2 into abillity to build a multi_phased extension? Like a blfs....

That could work for sure

**Comment by mkikets99** [comment]
Can you please add `Discussions` tab so we can discuss some small issues without making a *issue

**Comment by krglaws** [comment]
Done. I actually didn't know about that feature until now lol

**Comment by mkikets99** [comment]
Ok, so i am closing this issue.
It will be better to discuss that further at `Discussion` Tab
